# Copyright 2022 maksim
# See LICENSE file for licensing details.
#
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  server-port:
    default: 8000
    description: Default port on which FastAPI is available
    type: int
