# Copyright 2022 maksim
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  use-standalone-db:
    default: False
    description: Set to True if would like to use an external DB, not as related charm
    type: boolean

  postgres-ip:
    default: 127.0.0.1
    description: IP address of PostgreSQL database. (only if use-standalone-db is True)
    type: string

  postgres-port:
    default: 5432
    description: port of PostgreSQL database. (only if use-standalone-db is True)
    type: int

  postgres-username:
    default: demo-api-charm
    description: username of PostgreSQL database. (only if use-standalone-db is True)
    type: string

  postgres-password:
    default: mysecretpassword
    description: password of PostgreSQL database. (only if use-standalone-db is True)
    type: string
