[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "api_demo_server"
description = """FastAPI demo server"""
authors = [{name = "Maksim Beliaev", email = "beliaev.m.s@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]

dependencies = [
    "fastapi==0.85",
    "uvicorn[standard]==0.18.3",
    "python-multipart==0.0.5",
    "psycopg2-binary==2.9.3",
    "starlette_exporter==0.14.0"
]

# development dependencies
[project.optional-dependencies]
test = [
    "pre-commit",
]

deploy = [
    "flit==3.7.1",
]